-- Trip Sarthi — Supabase schema
-- Run once in the Supabase SQL Editor (Dashboard → SQL Editor → New query → paste → Run)

create table if not exists public.settings (
  id int primary key,
  phone_display text not null default '',
  phone_e164 text not null default '',
  email text not null default '',
  address text not null default '',
  whatsapp_message text not null default '',
  hero_image text not null default '',
  about_image text not null default ''
);

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null,
  model text not null default '',
  seats int not null default 4,
  bags text not null default '2',
  rate int not null default 12,
  tag text not null default '',
  description text not null default '',
  image_url text not null default '',
  sort int not null default 99
);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  title text not null,
  meta text not null default '',
  price text not null default '',
  image_url text not null default '',
  sort int not null default 99
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  meta text not null default '',
  stars int not null default 5,
  quote text not null default '',
  sort int not null default 99
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  caption text not null default '',
  image_url text not null default '',
  span text not null default '',
  sort int not null default 99
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  num text not null default '',
  title text not null,
  description text not null default '',
  sort int not null default 99
);

create table if not exists public.features (
  id bigint generated by default as identity primary key,
  title text not null,
  sub text not null default '',
  sort int not null default 99
);

create table if not exists public.steps (
  id bigint generated by default as identity primary key,
  num text not null default '',
  title text not null,
  description text not null default '',
  sort int not null default 99
);

create table if not exists public.brand_values (
  id bigint generated by default as identity primary key,
  num text not null default '',
  title text not null,
  description text not null default '',
  sort int not null default 99
);

-- Key-value store for every editable text block on the site (CMS)
create table if not exists public.content (
  key text primary key,
  value text not null default ''
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  from_city text not null default '',
  to_city text not null default '',
  message text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

-- RLS: public can read site content; nobody (except service role) can write.
-- Enquiries are write-only for the public; only service role reads them.
alter table public.settings enable row level security;
alter table public.cars enable row level security;
alter table public.routes enable row level security;
alter table public.testimonials enable row level security;
alter table public.gallery enable row level security;
alter table public.services enable row level security;
alter table public.features enable row level security;
alter table public.steps enable row level security;
alter table public.brand_values enable row level security;
alter table public.content enable row level security;
alter table public.enquiries enable row level security;

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select using (true);
drop policy if exists "public read cars" on public.cars;
create policy "public read cars" on public.cars for select using (true);
drop policy if exists "public read routes" on public.routes;
create policy "public read routes" on public.routes for select using (true);
drop policy if exists "public read testimonials" on public.testimonials;
create policy "public read testimonials" on public.testimonials for select using (true);
drop policy if exists "public read gallery" on public.gallery;
create policy "public read gallery" on public.gallery for select using (true);
drop policy if exists "public read services" on public.services;
create policy "public read services" on public.services for select using (true);
drop policy if exists "public read features" on public.features;
create policy "public read features" on public.features for select using (true);
drop policy if exists "public read steps" on public.steps;
create policy "public read steps" on public.steps for select using (true);
drop policy if exists "public read brand_values" on public.brand_values;
create policy "public read brand_values" on public.brand_values for select using (true);
drop policy if exists "public read content" on public.content;
create policy "public read content" on public.content for select using (true);
